using libflow.stmts;

namespace librule.targets
{
    interface ITargetMetadata
    {
        bool IsVaild { get; }

        bool IsControl { get; }

        bool IsAutoGenerated { get; }

        string Visit(AstNodeVisitor<string> visitor);
    }
}
