using libflow.stmts;

namespace librule.targets
{
    class TargetStatement : ITargetMetadata
    {
        public TargetStatement(IAstNode control, bool isAutoGenerated)
        {
            Statement = control;
            IsAutoGenerated = isAutoGenerated;
            LocalNames = new HashSet<string>();
        }

        public IAstNode Statement { get; set; }

        public HashSet<string> LocalNames { get; }

        public bool IsControl => true;

        public bool IsAutoGenerated { get; }

        public bool IsVaild => true;

        public string Visit(AstNodeVisitor<string> visitor)
        {
            return Statement.Visit(visitor);
        }
    }
}
