using libflow.stmts;
using librule.utils;
using System.Text;

namespace librule.targets
{
    class TargetMetadata : DynamicArray<TargetMetadataStep>, ITargetMetadata
    {
        public TargetMetadata(int size)
            : base(size)
        {
        }

        public TargetMetadata(TargetMetadataStep step)
            : this(1)
        {
            this[0] = step;
        }

        public string Name { get; }

        public bool IsControl => false;

        public bool IsCall => false;

        public bool IsAutoGenerated => false;

        public bool IsVaild => true; // this.SelectMany(x => x.Values).Count() > 1 && !this.SelectMany(x => x.Values).Same();

        public string Visit(AstNodeVisitor<string> visitor) 
        {
            var sb = new StringBuilder();
            for (var i = 0; i < Length; i++)
            {
                var ctx = this[i];
                for (var x = 0; x < ctx.Values.Count; x++)
                {
                    sb.Append(ctx.Values[x]);
                    if (ctx.IsResult)
                    {
                        if (x == ctx.Values.Count - 1 && i + 1 < this.Length)
                        {
                            if (this[i + 1].Values[0][0] != '=')
                            {
                                sb.Append('=');
                            }
                        }
                        else
                        {
                            sb.Append('=');
                        }
                    }
                }
            }

            return sb.ToString();
        }
    }
}
